import { 
  AdminUser, 
  AdminRole, 
  AdmissionApplication, 
  EnquiryLead, 
  StudentRecord, 
  TeacherRecord, 
  AdminCourse, 
  AdminBatch, 
  BatchAttendanceRecord, 
  PaymentReceipt, 
  ExamRecord, 
  StudentResultEntry, 
  StudyMaterial, 
  Assignment, 
  CertificateRecord, 
  NotificationItem, 
  AuditLogItem, 
  ToastMessage 
} from './types';

// Default Admin Users for Each Role
export const DEFAULT_ADMIN_USERS: AdminUser[] = [
  {
    id: 'USR-SUPER',
    name: 'Er. Raushan Kumar',
    email: 'director@thefuturetrack.in',
    phone: '+91 93088 77375',
    role: 'Super Admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
    status: 'Active',
    lastLogin: 'Just now',
  },
  {
    id: 'USR-ADMIN',
    name: 'Vikramaditya Verma',
    email: 'admin@thefuturetrack.in',
    phone: '+91 98765 43210',
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
    status: 'Active',
    lastLogin: 'Today, 09:30 AM',
  },
  {
    id: 'USR-ACCT',
    name: 'Prof. Anjali Sharma',
    email: 'accounts@thefuturetrack.in',
    phone: '+91 91234 56789',
    role: 'Accountant',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=300&auto=format&fit=crop',
    status: 'Active',
    lastLogin: 'Today, 10:15 AM',
  },
  {
    id: 'USR-TEACHER',
    name: 'Priyanka Kushwaha',
    email: 'faculty@thefuturetrack.in',
    phone: '+91 93456 78901',
    role: 'Teacher',
    avatar: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?q=80&w=300&auto=format&fit=crop',
    status: 'Active',
    lastLogin: 'Yesterday',
    assignedCourses: ['ADCA', 'DCA', 'Typing', 'DTP'],
    assignedBatches: ['ADCA Morning 2026', 'Tally Prime Evening'],
  },
  {
    id: 'USR-ADMISSION',
    name: 'Suman Roy',
    email: 'admissions@thefuturetrack.in',
    phone: '+91 94567 89012',
    role: 'Admission Manager',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop',
    status: 'Active',
    lastLogin: 'Today, 08:45 AM',
  },
  {
    id: 'USR-CONTENT',
    name: 'Amitav Sen',
    email: 'content@thefuturetrack.in',
    phone: '+91 95678 90123',
    role: 'Content Manager',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=300&auto=format&fit=crop',
    status: 'Active',
    lastLogin: '02 Oct 2026',
  },
];

// Role Permissions Matrix
export const ROLE_PERMISSIONS: Record<AdminRole, string[]> = {
  'Super Admin': [
    'dashboard', 'admissions', 'students', 'teachers', 'courses', 'batches', 
    'attendance', 'fees', 'exams', 'materials', 'assignments', 'certificates', 
    'cms', 'gallery', 'testimonials', 'blog', 'faq', 'notifications', 
    'reports', 'users', 'settings', 'logs', 'media'
  ],
  'Admin': [
    'dashboard', 'admissions', 'students', 'teachers', 'courses', 'batches', 
    'attendance', 'fees', 'exams', 'materials', 'assignments', 'certificates', 
    'cms', 'gallery', 'testimonials', 'blog', 'faq', 'notifications', 
    'reports', 'media', 'logs'
  ],
  'Accountant': [
    'dashboard', 'fees', 'students', 'reports', 'admissions'
  ],
  'Teacher': [
    'dashboard', 'courses', 'batches', 'students', 'attendance', 
    'exams', 'assignments', 'materials'
  ],
  'Admission Manager': [
    'dashboard', 'admissions', 'students', 'reports', 'notifications'
  ],
  'Content Manager': [
    'dashboard', 'cms', 'courses', 'gallery', 'testimonials', 
    'blog', 'faq', 'media'
  ],
};

// Initial 16 Courses matching the prompt requirements exactly
export const INITIAL_16_COURSES: AdminCourse[] = [
  {
    id: 'c-adca',
    name: 'ADCA (Advanced Diploma in Computer Applications)',
    slug: 'adca',
    category: 'Computer & Office',
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=600&auto=format&fit=crop',
    shortDescription: '12-Month flagship diploma covering computer fundamentals, MS Office 365, Tally Prime GST, DTP, and web essentials.',
    fullDescription: 'Comprehensive one-year computer application diploma designed to prepare students for government exams, corporate office roles, and computer management.',
    duration: '12 Months',
    eligibility: '10th / 12th Pass',
    level: 'All Levels',
    mode: 'Practical Lab',
    syllabus: ['Computer Fundamentals & OS', 'MS Word, Advanced Excel & PowerPoint', 'Tally Prime with GST & e-Filing', 'DTP (Photoshop & CorelDraw)', 'Internet Operations & Cyber Security', 'Capstone Project & Typing'],
    learningOutcomes: ['Complete office automation mastery', 'Computerized accounting proficiency', 'Professional bilingual typing speed'],
    certification: 'The Future Track Certified Advanced Diploma',
    assignedFaculty: 'Priyanka Kushwaha',
    status: 'Published',
    featured: true,
    seoTitle: 'ADCA Course in Dhanbad - The Future Track',
    seoDescription: 'Best 1-year ADCA diploma with hands-on computer lab training in Dhanbad.',
  },
  {
    id: 'c-2d-animation',
    name: '2D Animation & Motion Graphics',
    slug: '2d-animation',
    category: 'Creative',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Learn character animation, storyboarding, frame-by-frame motion, and digital illustration.',
    fullDescription: 'Professional 2D digital animation curriculum utilizing industry-standard vector motion tools for media production, advertisements, and cartoon development.',
    duration: '6 Months',
    eligibility: '10th Pass / Creative Interest',
    level: 'Intermediate',
    mode: 'Practical Lab',
    syllabus: ['Principles of Animation', 'Character Design & Rigging', 'Storyboarding & Scene Setup', 'Keyframing & Tweening', 'Sound Sync & Rendering'],
    learningOutcomes: ['Create commercial 2D cartoon clips', 'Character walk cycles and lip sync'],
    certification: 'Certificate in 2D Animation',
    assignedFaculty: 'Amitav Sen',
    status: 'Published',
    featured: false,
    seoTitle: '2D Animation Course - The Future Track',
    seoDescription: 'Master 2D animation and digital motion in Dhanbad.',
  },
  {
    id: 'c-tally-prime',
    name: 'Tally Prime & GST Accounting Master',
    slug: 'tally-prime',
    category: 'Accounting',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Practical business accounting, GST portal returns, TDS calculations, payroll, and corporate balance sheets.',
    fullDescription: 'In-depth commercial accounting program designed in collaboration with certified accountants for real company ledger and tax filing.',
    duration: '3 Months',
    eligibility: 'Commerce / Non-Commerce 12th Pass',
    level: 'Intermediate',
    mode: 'Practical Lab',
    syllabus: ['Principles of Accounting & Ledgers', 'Tally Prime Navigation & Company Setup', 'Inventory & Godown Tracking', 'GST Billing & E-Way Bills', 'TDS & Payroll Management', 'Final Accounts & Balance Sheet'],
    learningOutcomes: ['Independent corporate accounting capability', 'GST return filing and audit reconciliation'],
    certification: 'Professional Tally Prime & GST Specialist',
    assignedFaculty: 'Prof. Anjali Sharma',
    status: 'Published',
    featured: true,
    seoTitle: 'Tally Prime Course in Dhanbad - The Future Track',
    seoDescription: 'Hands-on Tally Prime with live GST billing in Dhanbad.',
  },
  {
    id: 'c-python-java',
    name: 'Python + Java Programming Combo',
    slug: 'python-java',
    category: 'AI & Technology',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Core and advanced object-oriented programming, data structures, and backend development in Python and Java.',
    fullDescription: 'Designed for BCA, B.Tech, and coding aspirants wanting dual programming mastery across enterprise Java and modern Python stacks.',
    duration: '6 Months',
    eligibility: '12th Pass / Coding Interest',
    level: 'Intermediate',
    mode: 'Practical Lab',
    syllabus: ['Python Fundamentals & Scripting', 'OOPs in Python & File I/O', 'Core Java Architecture & JVM', 'Java Collections Framework', 'Multithreading & JDBC Connectivity', 'Mini Software Projects in both languages'],
    learningOutcomes: ['Solid algorithmic problem-solving', 'Object-oriented software development'],
    certification: 'Dual Programming Specialist Diploma',
    assignedFaculty: 'Er. Raushan Kumar',
    status: 'Published',
    featured: true,
    seoTitle: 'Python & Java Training - The Future Track',
    seoDescription: 'Industry-standard Python and Java courses in Dhanbad.',
  },
  {
    id: 'c-job-oriented',
    name: 'Job-Oriented Professional IT Diploma',
    slug: 'job-oriented-course',
    category: 'Career',
    thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'All-inclusive career bootcamp combining office software, web technologies, soft skills, and interview coaching.',
    fullDescription: 'Tailored for graduates and college passouts wanting immediate workplace readiness with guaranteed mock interviews and resume building.',
    duration: '6 Months',
    eligibility: 'Any Graduate / 12th Pass',
    level: 'All Levels',
    mode: 'Hybrid (Lab + Online)',
    syllabus: ['Advanced Computer Automation', 'Business Communication & Email Writing', 'Financial Recordkeeping', 'Front-End Web Basics', 'Resume & Corporate Interview Preparation'],
    learningOutcomes: ['Guaranteed workplace confidence', 'Interview cleared portfolio'],
    certification: 'Job-Ready Certified IT Professional',
    assignedFaculty: 'Er. Raushan Kumar',
    status: 'Published',
    featured: true,
    seoTitle: 'Job Oriented IT Course in Dhanbad - The Future Track',
    seoDescription: 'High-placement computer training course in Dhanbad.',
  },
  {
    id: 'c-digital-marketing',
    name: 'Digital Marketing & SEO Specialist',
    slug: 'digital-marketing',
    category: 'Digital Business',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Search engine optimization, Google Ads, Meta Ads (Facebook & Instagram), and lead generation campaigns.',
    fullDescription: 'Hands-on practical training with live budget simulations on Google Ads and Meta platforms to drive business traffic and sales.',
    duration: '3 Months',
    eligibility: '12th Pass / Open to All',
    level: 'All Levels',
    mode: 'Hybrid (Lab + Online)',
    syllabus: ['SEO On-Page & Off-Page Fundamentals', 'Google Search & Display Advertising', 'Facebook & Instagram Ads Manager', 'Social Media Strategy & Canva Creatives', 'Email Funnels & Web Analytics'],
    learningOutcomes: ['Execute live paid ad campaigns', 'Rank websites on Google search results'],
    certification: 'Certified Digital Marketing Strategist',
    assignedFaculty: 'Amitav Sen',
    status: 'Published',
    featured: false,
    seoTitle: 'Digital Marketing Course Dhanbad - The Future Track',
    seoDescription: 'Practical SEO and social media marketing training in Dhanbad.',
  },
  {
    id: 'c-ai-automation',
    name: 'AI Automation & Prompt Engineering',
    slug: 'ai-automation',
    category: 'AI & Technology',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Master Generative AI, ChatGPT/Gemini API prompts, workflow automation bots, and modern AI productivity tools.',
    fullDescription: 'Next-generation syllabus empowering students with cutting-edge artificial intelligence prompt methodologies, custom GPTs, and workflow integrations.',
    duration: '3 Months',
    eligibility: 'Basic Computer Knowledge',
    level: 'Beginner',
    mode: 'Practical Lab',
    syllabus: ['Understanding LLMs & Generative AI', 'Advanced Prompt Engineering Patterns', 'Automating Excel, Word & Reports with AI', 'Building Custom Agents & Workflows', 'Ethics, Safety & Intellectual Property'],
    learningOutcomes: ['10x daily office and coding productivity', 'Automated business task pipelines'],
    certification: 'Certified AI & Automation Practitioner',
    assignedFaculty: 'Er. Raushan Kumar',
    status: 'Published',
    featured: true,
    seoTitle: 'AI Automation Course in Dhanbad - The Future Track',
    seoDescription: 'Learn prompt engineering and generative AI in Dhanbad.',
  },
  {
    id: 'c-dtp',
    name: 'DTP (Desktop Publishing) Master',
    slug: 'dtp',
    category: 'Creative',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'PageMaker, Photoshop, and CorelDraw for newspaper design, wedding cards, flex banners, and print publications.',
    fullDescription: 'Classic commercial publishing training covering prepress color theory, multi-page book layouts, printing press operations, and regional font typing.',
    duration: '3 Months',
    eligibility: '10th Pass',
    level: 'Beginner',
    mode: 'Practical Lab',
    syllabus: ['CorelDraw Vector Layouts & Logos', 'Adobe Photoshop Photo Editing & Cutouts', 'Adobe PageMaker / InDesign Formatting', 'Flex Banners, Pamphlets & Wedding Cards', 'Hindi & English Typography for Print'],
    learningOutcomes: ['Run an independent commercial printing/DTP center', 'Commercial prepress production'],
    certification: 'Diploma in Desktop Publishing (DTP)',
    assignedFaculty: 'Amitav Sen',
    status: 'Published',
    featured: false,
    seoTitle: 'DTP Course in Dhanbad - The Future Track',
    seoDescription: 'PageMaker, Photoshop and CorelDraw publishing course in Dhanbad.',
  },
  {
    id: 'c-video-editing',
    name: 'Video Editing & Motion Post-Production',
    slug: 'video-editing',
    category: 'Creative',
    thumbnail: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Adobe Premiere Pro, After Effects, color grading, sound design, and YouTube/Reels video production.',
    fullDescription: 'Comprehensive post-production masterclass for editing commercial advertisements, wedding videos, cinematic trailers, and social media reels.',
    duration: '3 Months',
    eligibility: '10th / 12th Pass',
    level: 'Intermediate',
    mode: 'Practical Lab',
    syllabus: ['Premiere Pro Timeline & Cutting Techniques', 'Color Correction & LUTs Application', 'Sound Design, BGM & Noise Reduction', 'After Effects Visual Effects & Lower Thirds', 'Export Formats for 4K & Instagram Reels'],
    learningOutcomes: ['Edit broadcast quality video projects', 'Motion title graphics creation'],
    certification: 'Professional Video Editor Certificate',
    assignedFaculty: 'Amitav Sen',
    status: 'Published',
    featured: false,
    seoTitle: 'Video Editing Course in Dhanbad - The Future Track',
    seoDescription: 'Learn Premiere Pro & After Effects video editing in Dhanbad.',
  },
  {
    id: 'c-graphic-design',
    name: 'Graphic Design & UI/UX Multimedia',
    slug: 'graphic-design',
    category: 'Creative',
    thumbnail: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Brand identity, logos, vector illustration, social media creatives, and Figma website/app UI design.',
    fullDescription: 'Full creative curriculum covering color harmony, grid systems, commercial iconography, wireframing, and interactive app prototyping.',
    duration: '4 Months',
    eligibility: 'Open to All',
    level: 'Beginner',
    mode: 'Practical Lab',
    syllabus: ['Design Principles & Visual Hierarchy', 'Photoshop Photo Retouching & Compositing', 'Illustrator Vector Branding & Logos', 'Figma Wireframing & App UI Prototyping', 'Client Presentation & Behance Portfolio'],
    learningOutcomes: ['Build a professional client portfolio', 'Design intuitive modern mobile and web interfaces'],
    certification: 'Diploma in Graphic Design & UI/UX',
    assignedFaculty: 'Amitav Sen',
    status: 'Published',
    featured: true,
    seoTitle: 'Graphic Design Course in Dhanbad - The Future Track',
    seoDescription: 'Master Photoshop, Illustrator & Figma design in Dhanbad.',
  },
  {
    id: 'c-typing',
    name: 'Computer Typing Master (English & Hindi Kruti Dev)',
    slug: 'typing',
    category: 'Computer & Office',
    thumbnail: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Touch typing speed building in English and Hindi (Kruti Dev & Remington GAIL) for govt. court and clerical exams.',
    fullDescription: 'Structured daily typing practice with speed diagnostic software, error analysis, and timed tests matching SSC, High Court, and Railway typing standards.',
    duration: '2 Months',
    eligibility: 'No Qualification Bar',
    level: 'Beginner',
    mode: 'Practical Lab',
    syllabus: ['Finger Placement & Home Row Discipline', 'English Touch Typing Practice (35-45+ WPM)', 'Hindi Kruti Dev 010 Font Mastery', 'Remington GAIL & Mangal Inscript Layouts', 'Govt. Typing Exam Mock Tests'],
    learningOutcomes: ['Achieve 35+ WPM in English, 30+ WPM in Hindi', 'Official speed verification certificate'],
    certification: 'Speed Typing Master Certificate (WPM Verified)',
    assignedFaculty: 'Priyanka Kushwaha',
    status: 'Published',
    featured: false,
    seoTitle: 'Hindi & English Typing Classes Dhanbad - The Future Track',
    seoDescription: 'Govt. exam typing speed training in Dhanbad.',
  },
  {
    id: 'c-dfa',
    name: 'DFA (Diploma in Financial Accounting)',
    slug: 'dfa',
    category: 'Accounting',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Double-entry bookkeeping, MS Excel financial modeling, computerized accounting, and audit voucher verification.',
    fullDescription: '6-month comprehensive accounting diploma designed for non-commerce and commerce students preparing for cashier, accountant, or billing roles.',
    duration: '6 Months',
    eligibility: '12th Pass',
    level: 'Intermediate',
    mode: 'Classroom',
    syllabus: ['Financial Accounting Principles', 'Advanced Excel Financial Functions', 'Tally Prime Fundamental to Advanced', 'Taxation Basics (GST & Income Tax)', 'Bank Reconciliation Statements (BRS)', 'Practical Accounting Project'],
    learningOutcomes: ['Manage complete institutional or retail accounts', 'Prepare accurate balance sheets and profit & loss statements'],
    certification: 'Diploma in Financial Accounting (DFA)',
    assignedFaculty: 'Prof. Anjali Sharma',
    status: 'Published',
    featured: false,
    seoTitle: 'DFA Course in Dhanbad - The Future Track',
    seoDescription: '6-Month financial accounting diploma in Dhanbad.',
  },
  {
    id: 'c-account-course',
    name: 'Commercial Accounting & Taxation Certificate',
    slug: 'account-course',
    category: 'Accounting',
    thumbnail: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Core accounting fundamentals, ledger posting, trial balance, GST invoices, and banking transactions.',
    fullDescription: 'Fast-track short term accounting certificate tailored for shop owners, retail managers, and beginners wanting to understand business ledger balances.',
    duration: '2 Months',
    eligibility: '10th / 12th Pass',
    level: 'Beginner',
    mode: 'Practical Lab',
    syllabus: ['Cash Book & Day Book Entries', 'Bank Deposit & Cheque Processing', 'Journal Entries & Ledger Accounts', 'GST Invoice Preparation', 'Basic Excel Bookkeeping'],
    learningOutcomes: ['Maintain daily commercial shop and business accounts', 'Accurate invoice creation'],
    certification: 'Commercial Accounting Certificate',
    assignedFaculty: 'Prof. Anjali Sharma',
    status: 'Published',
    featured: false,
    seoTitle: 'Basic Accounting Course - The Future Track',
    seoDescription: 'Practical business bookkeeping training in Dhanbad.',
  },
  {
    id: 'c-ecommerce',
    name: 'E-Commerce Management & Online Business',
    slug: 'e-commerce',
    category: 'Digital Business',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0a67e557224f?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Store creation on Shopify, Amazon/Flipkart seller onboarding, product cataloging, payment gateways, and shipping logistics.',
    fullDescription: 'Everything needed to launch and run a profitable online store in India, from supplier sourcing to listing optimization and courier tie-ups.',
    duration: '3 Months',
    eligibility: '12th Pass / Entrepreneurs',
    level: 'All Levels',
    mode: 'Hybrid (Lab + Online)',
    syllabus: ['E-Commerce Models (B2C, B2B, D2C)', 'Setting Up Shopify & WooCommerce Stores', 'Amazon & Flipkart Seller Central Registration', 'Product Photography & Listing SEO', 'Payment Gateways (Razorpay/UPI) & Logistics Setup'],
    learningOutcomes: ['Launch your own live e-commerce store', 'Manage marketplace product listings and orders'],
    certification: 'Certificate in E-Commerce Management',
    assignedFaculty: 'Amitav Sen',
    status: 'Published',
    featured: false,
    seoTitle: 'E-Commerce Course in Dhanbad - The Future Track',
    seoDescription: 'Amazon, Flipkart and Shopify business course in Dhanbad.',
  },
  {
    id: 'c-web-development',
    name: 'Full Stack Website Development (MERN Stack)',
    slug: 'website-development',
    category: 'AI & Technology',
    thumbnail: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'HTML5, modern CSS, JavaScript ES6+, React.js, Node.js, Express, MongoDB Atlas, and Git deployment.',
    fullDescription: 'Intensive 6-month software development program training students to engineer complete responsive web applications with secure backend APIs and databases.',
    duration: '6 Months',
    eligibility: '12th Pass / BCA / BSc IT / Any Graduate',
    level: 'Intermediate',
    mode: 'Practical Lab',
    syllabus: ['HTML5 Semantic Markup & CSS3 Layouts', 'Tailwind CSS & Responsive Web Architecture', 'Modern JavaScript (ES6+, Async/Await, Fetch)', 'React Framework (Hooks, State, Router)', 'Node.js & Express RESTful API Engineering', 'MongoDB Databases & Cloud Deployment on Vercel'],
    learningOutcomes: ['Deploy full-stack web applications on cloud', 'Build dynamic RESTful APIs and modern frontend interfaces'],
    certification: 'Full Stack Web Developer Diploma',
    assignedFaculty: 'Er. Raushan Kumar',
    status: 'Published',
    featured: true,
    seoTitle: 'Full Stack Web Development in Dhanbad - The Future Track',
    seoDescription: 'MERN stack coding bootcamp in Dhanbad.',
  },
  {
    id: 'c-website-creation',
    name: 'No-Code Website Creation & WordPress CMS',
    slug: 'website-creation',
    category: 'Digital Business',
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=600&auto=format&fit=crop',
    shortDescription: 'Build professional business websites, blogs, and portfolio sites using WordPress, Elementor, and modern no-code builders.',
    fullDescription: 'Ideal for non-programmers, small business owners, and freelancers who want to design high-converting, mobile-responsive websites in hours without coding.',
    duration: '2 Months',
    eligibility: 'Open to All',
    level: 'Beginner',
    mode: 'Practical Lab',
    syllabus: ['Domain, Hosting & DNS Setup', 'WordPress Installation & Dashboard Tour', 'Elementor Page Builder Deep Dive', 'Theme Customization & Mobile Responsiveness', 'Form Integrations & Security Plugins'],
    learningOutcomes: ['Build and launch complete business websites in days', 'Deliver freelance client websites independently'],
    certification: 'Certificate in Website Creation & WordPress',
    assignedFaculty: 'Priyanka Kushwaha',
    status: 'Published',
    featured: false,
    seoTitle: 'WordPress Website Creation Course - The Future Track',
    seoDescription: 'No-code web design training in Dhanbad.',
  },
];

// Initial Students Data with verified Dhanbad context
export const INITIAL_STUDENTS: StudentRecord[] = [
  {
    id: 'TFT-2025-0842',
    name: 'Aman Kushwaha',
    guardianName: 'Manoj Kushwaha',
    email: 'aman.k@student.thefuturetrack.edu.in',
    phone: '+91 98765 12345',
    whatsapp: '+91 98765 12345',
    address: 'Near Bartand Bus Stand, Dhanbad, Jharkhand',
    dob: '12-08-2004',
    gender: 'Male',
    course: 'ADCA (Advanced Diploma in Computer Applications)',
    batchId: 'B-ADCA-01',
    batchTime: 'Morning Batch (10:00 AM - 12:00 PM)',
    admissionDate: '15-07-2025',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=300&auto=format&fit=crop',
    status: 'Active',
    attendancePercentage: 92,
    overallScore: 88,
    feeStatus: 'Paid',
    totalFee: 12000,
    paidFee: 12000,
    remainingFee: 0,
    nextDueDate: 'None (Completed)',
    documents: [
      { id: 'doc-1', name: 'Aadhaar Card Copy', type: 'PDF', uploadDate: '15-07-2025', verified: true },
      { id: 'doc-2', name: '10th Board Marksheet', type: 'PDF', uploadDate: '15-07-2025', verified: true },
      { id: 'doc-3', name: 'Passport Photo', type: 'JPG', uploadDate: '15-07-2025', verified: true },
    ],
    notes: 'Excellent performance in Excel formulas and typing tests.',
  },
  {
    id: 'TFT-2025-0891',
    name: 'Sneha Kumari',
    guardianName: 'Sanjay Kumar',
    email: 'sneha.k@gmail.com',
    phone: '+91 94311 88234',
    whatsapp: '+91 94311 88234',
    address: 'Jharudih, Dhanbad, Jharkhand 826001',
    dob: '05-11-2005',
    gender: 'Female',
    course: 'Tally Prime & GST Accounting Master',
    batchId: 'B-TALLY-02',
    batchTime: 'Mid-Morning (11:30 AM - 01:00 PM)',
    admissionDate: '10-08-2025',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=300&auto=format&fit=crop',
    status: 'Active',
    attendancePercentage: 96,
    overallScore: 94,
    feeStatus: 'Paid',
    totalFee: 6500,
    paidFee: 6500,
    remainingFee: 0,
    nextDueDate: 'Completed',
    documents: [
      { id: 'doc-1', name: 'Aadhaar Card', type: 'PDF', uploadDate: '10-08-2025', verified: true },
      { id: 'doc-2', name: '12th Commerce Certificate', type: 'PDF', uploadDate: '10-08-2025', verified: true },
    ],
    notes: 'Preparing for CA firm tax internship.',
  },
  {
    id: 'TFT-2026-0104',
    name: 'Vikas Sharma',
    guardianName: 'Ramesh Sharma',
    email: 'vikas.dev@gmail.com',
    phone: '+91 87654 32190',
    whatsapp: '+91 87654 32190',
    address: 'City Centre Market, Dhanbad, Jharkhand',
    dob: '22-03-2003',
    gender: 'Male',
    course: 'Full Stack Website Development (MERN Stack)',
    batchId: 'B-DEV-01',
    batchTime: 'Evening Batch (04:00 PM - 06:00 PM)',
    admissionDate: '05-01-2026',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=300&auto=format&fit=crop',
    status: 'Active',
    attendancePercentage: 88,
    overallScore: 85,
    feeStatus: 'Partial',
    totalFee: 18000,
    paidFee: 10000,
    remainingFee: 8000,
    nextDueDate: '15-10-2026',
    documents: [
      { id: 'doc-1', name: 'Aadhaar Card', type: 'PDF', uploadDate: '05-01-2026', verified: true },
      { id: 'doc-2', name: 'Graduation Degree', type: 'PDF', uploadDate: '05-01-2026', verified: true },
    ],
    notes: 'Installment 2 scheduled for 15 October.',
  },
  {
    id: 'TFT-2026-0219',
    name: 'Neha Patel',
    guardianName: 'Dinesh Patel',
    email: 'neha.patel99@gmail.com',
    phone: '+91 76543 21098',
    whatsapp: '+91 76543 21098',
    address: 'Bank More, Dhanbad, Jharkhand',
    dob: '18-09-2004',
    gender: 'Female',
    course: 'Graphic Design & UI/UX Multimedia',
    batchId: 'B-DESIGN-01',
    batchTime: 'Morning Batch (08:00 AM - 10:00 AM)',
    admissionDate: '12-02-2026',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=300&auto=format&fit=crop',
    status: 'Active',
    attendancePercentage: 90,
    overallScore: 91,
    feeStatus: 'Paid',
    totalFee: 8000,
    paidFee: 8000,
    remainingFee: 0,
    nextDueDate: 'Completed',
    documents: [
      { id: 'doc-1', name: 'Aadhaar Card', type: 'PDF', uploadDate: '12-02-2026', verified: true },
    ],
    notes: 'Outstanding skills in Photoshop composite art.',
  },
];

// Initial Batches
export const INITIAL_BATCHES: AdminBatch[] = [
  {
    id: 'B-ADCA-01',
    name: 'ADCA Regular Morning Batch',
    courseId: 'c-adca',
    courseName: 'ADCA (Advanced Diploma in Computer Applications)',
    teacherId: 'fac-priyanka',
    teacherName: 'Priyanka Kushwaha',
    startDate: '01-08-2025',
    endDate: '31-07-2026',
    classDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    roomLab: 'Computer Lab 1 (Workstations 1-20)',
    maxStudents: 20,
    enrolledStudentsCount: 18,
    status: 'Active',
  },
  {
    id: 'B-TALLY-02',
    name: 'Tally Prime Fast-Track Batch',
    courseId: 'c-tally-prime',
    courseName: 'Tally Prime & GST Accounting Master',
    teacherId: 'fac-anjali',
    teacherName: 'Prof. Anjali Sharma',
    startDate: '15-08-2025',
    endDate: '15-11-2025',
    classDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    startTime: '11:30 AM',
    endTime: '01:00 PM',
    roomLab: 'Accounting Lab 2',
    maxStudents: 15,
    enrolledStudentsCount: 14,
    status: 'Active',
  },
  {
    id: 'B-DEV-01',
    name: 'Full Stack Coding Evening Batch',
    courseId: 'c-web-development',
    courseName: 'Full Stack Website Development (MERN Stack)',
    teacherId: 'fac-director',
    teacherName: 'Er. Raushan Kumar',
    startDate: '10-01-2026',
    endDate: '10-07-2026',
    classDays: ['Mon', 'Wed', 'Fri', 'Sat'],
    startTime: '04:00 PM',
    endTime: '06:00 PM',
    roomLab: 'Software Lab 3',
    maxStudents: 16,
    enrolledStudentsCount: 12,
    status: 'Active',
  },
  {
    id: 'B-AI-01',
    name: 'AI & Automation Weekend Special',
    courseId: 'c-ai-automation',
    courseName: 'AI Automation & Prompt Engineering',
    teacherId: 'fac-director',
    teacherName: 'Er. Raushan Kumar',
    startDate: '01-10-2026',
    endDate: '31-12-2026',
    classDays: ['Sat', 'Sun'],
    startTime: '02:00 PM',
    endTime: '05:00 PM',
    roomLab: 'Innovation Lab 1',
    maxStudents: 20,
    enrolledStudentsCount: 9,
    status: 'Upcoming',
  },
];

// Initial Admission Leads & Enquiries
export const INITIAL_ENQUIRIES: EnquiryLead[] = [
  {
    id: 'ENQ-9041',
    name: 'Pooja Kumari',
    phone: '+91 98351 22345',
    whatsapp: '+91 98351 22345',
    email: 'pooja.k@gmail.com',
    interestedCourse: 'ADCA (Advanced Diploma in Computer Applications)',
    source: 'Website Form',
    message: 'Interested in 1-year diploma with Tally GST module. Want morning batch.',
    assignedStaff: 'Suman Roy',
    followUpDate: 'Today',
    status: 'New',
    notes: 'Called once, requested call back at 4 PM.',
    createdAt: 'Today, 10:15 AM',
  },
  {
    id: 'ENQ-9040',
    name: 'Amit Kumar Singh',
    phone: '+91 87654 99120',
    whatsapp: '+91 87654 99120',
    email: 'amit.singh@yahoo.com',
    interestedCourse: 'Tally Prime & GST Accounting Master',
    source: 'Course Popup',
    message: 'Need urgent admission for commerce audit practice.',
    assignedStaff: 'Suman Roy',
    followUpDate: 'Tomorrow',
    status: 'Contacted',
    notes: 'Sent fee brochure over WhatsApp.',
    createdAt: 'Yesterday, 04:30 PM',
  },
  {
    id: 'ENQ-9039',
    name: 'Rohan Verma',
    phone: '+91 76543 88123',
    whatsapp: '+91 76543 88123',
    email: 'rohan.tech@gmail.com',
    interestedCourse: 'Full Stack Website Development (MERN Stack)',
    source: 'WhatsApp CTA',
    message: 'Want to switch from non-tech to frontend developer.',
    assignedStaff: 'Er. Raushan Kumar',
    followUpDate: '05-10-2026',
    status: 'Interested',
    notes: 'Demo class scheduled for Saturday 4 PM.',
    createdAt: '02-10-2026',
  },
  {
    id: 'ENQ-9038',
    name: 'Kavita Chawla',
    phone: '+91 91234 44556',
    whatsapp: '+91 91234 44556',
    email: 'kavita.c@gmail.com',
    interestedCourse: 'Graphic Design & UI/UX Multimedia',
    source: 'Walk-in',
    message: 'Visited campus with father. Checked lab facilities.',
    assignedStaff: 'Suman Roy',
    followUpDate: '04-10-2026',
    status: 'Follow-up',
    notes: 'Impression positive, comparing morning slots.',
    createdAt: '01-10-2026',
  },
];

// Initial Payment Receipts
export const INITIAL_PAYMENTS: PaymentReceipt[] = [
  {
    receiptNo: 'RCPT-2026-8422',
    studentId: 'TFT-2025-0842',
    studentName: 'Aman Kushwaha',
    courseName: 'ADCA (12 Months)',
    amount: 12000,
    paymentDate: '15-07-2025',
    paymentMethod: 'UPI',
    transactionId: 'UPI-98214472199',
    receivedBy: 'Prof. Anjali Sharma',
    notes: 'Full payment upfront with 10% annual scholarship discount.',
    balanceRemaining: 0,
  },
  {
    receiptNo: 'RCPT-2026-8423',
    studentId: 'TFT-2025-0891',
    studentName: 'Sneha Kumari',
    courseName: 'Tally Prime & GST Master',
    amount: 6500,
    paymentDate: '10-08-2025',
    paymentMethod: 'Cash',
    receivedBy: 'Prof. Anjali Sharma',
    notes: 'Paid at front cash counter.',
    balanceRemaining: 0,
  },
  {
    receiptNo: 'RCPT-2026-8424',
    studentId: 'TFT-2026-0104',
    studentName: 'Vikas Sharma',
    courseName: 'Full Stack Website Development',
    amount: 10000,
    paymentDate: '05-01-2026',
    paymentMethod: 'Bank Transfer',
    transactionId: 'NEFT-AXIS-009182',
    receivedBy: 'Prof. Anjali Sharma',
    notes: 'First installment paid. Next installment of ₹8,000 due in Oct.',
    balanceRemaining: 8000,
  },
];

// Initial Verifiable Certificates
export const INITIAL_CERTIFICATES: CertificateRecord[] = [
  {
    certificateNo: 'TFT-CERT-2025-9921',
    studentId: 'TFT-2025-0842',
    studentName: 'Aman Kushwaha',
    courseName: 'DCA (Diploma in Computer Applications)',
    issueDate: '20-12-2025',
    completionDate: '15-12-2025',
    grade: 'A+ (Distinction)',
    percentage: 92,
    authorizedPerson: 'Er. Raushan Kumar (Director)',
    verificationCode: 'VERIFY-TFT-9921',
    status: 'Issued',
  },
  {
    certificateNo: 'TFT-CERT-2026-1044',
    studentId: 'TFT-2025-0842',
    studentName: 'Aman Kushwaha',
    courseName: 'English & Hindi Speed Typing Master (45 WPM)',
    issueDate: '10-02-2026',
    completionDate: '08-02-2026',
    grade: 'Grade A',
    percentage: 88,
    authorizedPerson: 'Er. Raushan Kumar (Director)',
    verificationCode: 'VERIFY-TFT-1044',
    status: 'Issued',
  },
  {
    certificateNo: 'TFT-CERT-2025-8812',
    studentId: 'TFT-2025-0891',
    studentName: 'Sneha Kumari',
    courseName: 'Tally Prime & GST Accounting Master',
    issueDate: '28-11-2025',
    completionDate: '25-11-2025',
    grade: 'A+ (Distinction)',
    percentage: 94,
    authorizedPerson: 'Er. Raushan Kumar (Director)',
    verificationCode: 'VERIFY-TFT-8812',
    status: 'Issued',
  },
];

// Initial Study Materials
export const INITIAL_STUDY_MATERIALS: StudyMaterial[] = [
  {
    id: 'mat-1',
    title: 'ADCA Semester 1 Complete Computer Handbook',
    description: 'Hardware architecture, Windows 11 OS, and LibreOffice/Word comprehensive guide.',
    courseName: 'ADCA (Advanced Diploma in Computer Applications)',
    batchName: 'ADCA Regular Morning Batch',
    subject: 'Computer Fundamentals',
    uploadedBy: 'Priyanka Kushwaha',
    fileType: 'PDF',
    fileSize: '14.2 MB',
    fileUrl: '#',
    publishDate: '10-01-2026',
    status: 'Published',
  },
  {
    id: 'mat-2',
    title: 'Tally Prime Shortcut Keys & GST Cheatsheet',
    description: 'Quick reference for ledger keys, voucher shortcuts, and GST invoice configuration.',
    courseName: 'Tally Prime & GST Accounting Master',
    batchName: 'Tally Prime Fast-Track Batch',
    subject: 'Corporate Accounting',
    uploadedBy: 'Prof. Anjali Sharma',
    fileType: 'PDF',
    fileSize: '3.8 MB',
    fileUrl: '#',
    publishDate: '18-01-2026',
    status: 'Published',
  },
  {
    id: 'mat-3',
    title: 'MERN Stack REST API Starter Repository',
    description: 'Express.js backend boilerplate with JWT authentication and MongoDB schema.',
    courseName: 'Full Stack Website Development (MERN Stack)',
    batchName: 'Full Stack Coding Evening Batch',
    subject: 'Backend Engineering',
    uploadedBy: 'Er. Raushan Kumar',
    fileType: 'ZIP',
    fileSize: '8.4 MB',
    fileUrl: '#',
    publishDate: '12-02-2026',
    status: 'Published',
  },
];

// Initial Audit Logs
export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'LOG-001',
    user: 'Er. Raushan Kumar',
    userRole: 'Super Admin',
    action: 'Login',
    module: 'Authentication',
    details: 'Logged into Admin Console via Secure Session',
    timestamp: 'Today, 08:30 AM',
    ip: '192.168.1.101',
  },
  {
    id: 'LOG-002',
    user: 'Prof. Anjali Sharma',
    userRole: 'Accountant',
    action: 'Payment Recorded',
    module: 'Finance',
    details: 'Recorded fee receipt #RCPT-2026-8424 for student Vikas Sharma',
    timestamp: 'Today, 09:12 AM',
    ip: '192.168.1.104',
  },
  {
    id: 'LOG-003',
    user: 'Suman Roy',
    userRole: 'Admission Manager',
    action: 'Update',
    module: 'Admissions',
    details: 'Updated status of enquiry ENQ-9041 to Contacted',
    timestamp: 'Today, 10:20 AM',
    ip: '192.168.1.108',
  },
  {
    id: 'LOG-004',
    user: 'Er. Raushan Kumar',
    userRole: 'Super Admin',
    action: 'Certificate Issued',
    module: 'Certificates',
    details: 'Generated verifiable certificate TFT-CERT-2026-1044',
    timestamp: 'Yesterday, 04:45 PM',
    ip: '192.168.1.101',
  },
];
